### ISSUE TITLE
Browsing and downloading of repository logfiles

### ISSUE THREAD

**Issue by jgoldhammer** [AFaust/ootbee-support-tools#10]
Current log page allows to tail log files. It would be cool to manage logfiles via browser.

Possible features:
- download single files
- zip files into one node and allow downloading via alfresco webscript
- delete log files

**Comment by AFaust** [comment]
We have to be careful with this kind of features. The current functionality does not really access/tail the log files directly but injects an appender into the root logger and temporarily records/stores the log events.
Accessing the real log files will mean we are leaving a clean, isolated context and are providing (indirect) access to the server file system. If done incorrectly it could accidentally expose things we did not intend to (similar to crappy Surf resource handler + web resources in JARs).

Having said that I can see the benefit. Via the appender configuration properties (which we already access and display via "Show appender details") we can use the file path patterns to lookup eligible log files and restrict access only to those. Obviously older log files not matching any of the patterns will not be accessible. The feature would be limited to Log4J log files only. If an external logrotation functionality (logrotate.d) is configured it could cause older log files to be inaccessible.

As an administrator I would be somewhat anxious to allow deletion of log files via a web interface. The group of ALFRESCO_ADMINISTRATORS typically is != the group of server / system administrators that rely on such logs, and the latter typically does not (and potentially should not) trust the former to always to the right thing.
I can see these as features that could be enabled / disabled via alfresco-global.properties to deal with concerns that may arise. Come to think of it, all modification features of the support tools could probably do with this kind of enablement restriction (default would be "all allowed" as it is now).

**Comment by AFaust** [comment]
I'm just wondering about the "ZIP into Alfresco node and allow downloading via web script" - why should there be the intermediate step of creating an Alfresco node if it is just about downloading the log files? I already have a web script to download the individual logs and another script to provide a ZIP download would be a simple thing to add. The only additional benefit of ZIP-ing them to a node first would be support of "Byte-Range" requests, while a simple ZIP download would have to be a one-shot operation.

**Comment by AFaust** [comment]
Support for deleting single log files and downloading multiple as ZIP has been added.

**Comment by AntonioSoler** [comment]
As Axel mentioned when I originally designed this I had 2 clear ideas in mind:

1) This does not replace the log file administration by the server sysadmin, if you need to access the log remotely to diagnose what is happening because there is a performance issue on the environment you need something really lightweight, you cannot add any minimal overhead to an already overloaded environment. That's why I picked the log4j appender method.

2) Most of the tools should be "hotdeployable" to be able to deploy them on an already running environment (if you need to reboot the tomcat server to deploy the tools you may hide the issue). This with the use of an appender and the JMX persisted values where the only 2 functionalities that would not work in a hotdeploy...  I would encourage you to keep this philosophy: keep the module the less intrusive were possible.

**Comment by jgoldhammer** [comment]
@AFaust For me it does not show up any menu for log files in the admin tools section using the current state...

![image](https://cloud.githubusercontent.com/assets/3872101/20155011/2fce5620-a6ca-11e6-961f-ae8859986811.png)

![image](https://cloud.githubusercontent.com/assets/3872101/20154997/211f5a34-a6ca-11e6-84ad-a3b63c6d6ab1.png)

But I can directly access it by url:
![image](https://cloud.githubusercontent.com/assets/3872101/20155120/ab85e512-a6ca-11e6-9713-999ca38bbe47.png)

**Comment by AFaust** [comment]
I should have mentioned it is accessible from the Log4J Settings tool - similar to log tailing.

**Comment by jgoldhammer** [comment]
In general, very good feature. I like it very much!

Some hints to UI:
- Can you format the logfile size to MB (e.g. by using FileUtils.byteCountToDisplaySize)?
- Can you use datatables for ui to have row sorting? 

Bugs:
- Direct download and deleting of logfiles does not work - "The log file path could not be resolved to a valid log file - access to any other file system contents is forbidden via this web script"
![image](https://cloud.githubusercontent.com/assets/3872101/20155334/a6da29b4-a6cb-11e6-9ddd-95c85c3b91b4.png)

- tailing logfile does not work anymore (empty screen)- maybe a side effect?

**Comment by AFaust** [comment]
What OS are you running this on? Maybe there is a difference in path handling and the assumptions I make in the code about "valid" log file paths vs. other files do not hold true for other OSes / file systems.

I'll check tailing on my dev system. There should have been no side effect as that web script has not been touched as far as I am aware of.

**Comment by AFaust** [comment]
org.apache.commons.io.FileUtils.byteCountToDisplaySize does not handle I18n and incorrectly uses decimal-based units instead of proper binary-based ones, despite using binary-based conversion. So I'll have to roll my own.

**Comment by jgoldhammer** [comment]
Running on MacOS/Darwin...

For Log tailing there are no results coming from backend...
![image](https://cloud.githubusercontent.com/assets/3872101/20155587/d44efbee-a6cc-11e6-925a-e731fb6f1912.png)

**Comment by AFaust** [comment]
Stupid question: Have you set any logger to produce output or triggered an action that produces output? I have set the (root logger) to debug and was swamped with messages.
Also, keep in mind my previous comments: The tailing operation does NOT access the log file - instead it adds a temporary appender to the root logger and only begins to collect log events the moment you start it. So you will not see the last messages before you started it.
This limitation has been made consciously to avoid requiring the same kind of log4j.properties setup requirement necessary for the JMX logger in the Enterprise Alfresco Admin Tools.

![tailing](https://cloud.githubusercontent.com/assets/2211521/20155933/66a8ba38-a6ce-11e6-8e9e-f077a61f403f.png)

**Comment by jgoldhammer** [comment]
Sorry, you are right- have not seen that I have not set the root logger to Debug. It is too late today :-)
Thx, Axel!

**Comment by AFaust** [comment]
Row sorting on Repository-tier log file dialog has been added.
I have consolidated / updated some of the log file path handling to avoid issues with forward vs. backward slash handling. But since I do not have access to any MacOS system I can neither re-test nor debug any issues - I'd need some example file path URLs to reconstruct any issues.

**Comment by jgoldhammer** [comment]
Thanks for the update.

Example path which is generated as download link:

http://localhost:8080/alfresco/s/ootbee/admin/log4j-log-file/Users/jgoldhammer/development/sources/ootbee-support-tools/repository/target/alfresco.log.2016-10-31

![image](https://cloud.githubusercontent.com/assets/3872101/20249217/d03b2926-a9f4-11e6-8326-9cea674c5685.png)

The error message looks like this:

![image](https://cloud.githubusercontent.com/assets/3872101/20249221/eb5ebdbc-a9f4-11e6-9573-8087d7d729cf.png)

**Comment by AFaust** [comment]
Ah - I can imagine what the problem is. The proper path in your case is very likely /Users/jgoldhammer/development/sources/ootbee-support-tools/repository/target/alfresco.log.2016-10-31 while the effective path being evaluated is Users/jgoldhammer/development/sources/ootbee-support-tools/repository/target/alfresco.log.2016-10-31 (without the leading slash and thus relative to the Alfresco process working directory).
I will investigate how best to pass the leading slash without messing up path handling for OS / file systems without a leading slash. Simply encoding the slash will not work as %2F in the path causes Tomcat to stop processing the request alltogether (a security mechanism to specifically avoid passing URL encoded, unsafe paths that may be used for file access).

**Comment by jgoldhammer** [comment]
Thanks for the update, @AFaust.
I have created a PR after debugging the code and found out that the path check does not work as suggested...

**Comment by jgoldhammer** [comment]
Another question: Why is the formatted file size displayed in a tooltip only?

**Comment by AFaust** [comment]
So it is consistent with the date where the formatted value is also provided via the title.

**Comment by AFaust** [comment]
@jgoldhammer I had to redo the change of the PR since the result failed to work on Windows afterwards. I think my initial code tried to do the right thing (compare the file name for potential suffixes due rotation / compression) but was incomplete. Hopefully now the path check works on all platforms.

**Comment by jgoldhammer** [comment]
For me it is working now. Thanks!
